DROP DATABASE IF EXISTS reviews_api;
CREATE DATABASE reviews_api;
\c reviews_api;

DROP TABLE if exists reviews CASCADE;
DROP TABLE if exists reviews_photos CASCADE;
DROP TABLE if exists characteristics CASCADE;
DROP TABLE if exists characteristic_reviews CASCADE;
DROP TABLE if exists metadata CASCADE;

CREATE TABLE reviews (
  id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  product_id int not null,
  rating int not null,
  review_date bigint not null,
  summary varchar(200) not null,
  body varchar(1000) not null,
  recommend boolean not null default false,
  reported boolean not null default false,
  reviewer_name varchar(50) not null,
  reviewer_email varchar(50) not null,
  response varchar(200) ,
  helpfulness int not null default 0
);

CREATE TABLE reviews_photos (
  id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  review_id int references reviews(id),
  url varchar(300)
);

CREATE TABLE characteristics (
  id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  product_id int,
  name varchar (20)
);

CREATE TABLE characteristic_reviews (
  id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  characteristic_id int references characteristics(id),
  review_id int references reviews(id),
  value int
);

-- insert csv data into tables
COPY reviews (id, product_id, rating, review_date, summary, body, recommend, reported, reviewer_name, reviewer_email, response, helpfulness)
FROM '/Users/kevinkimchii/Documents/hackreactor/hrlax49/SDC/data/reviews.csv'
DELIMITER ','
CSV HEADER;

COPY reviews_photos (id, review_id, url)
FROM '/Users/kevinkimchii/Documents/hackreactor/hrlax49/SDC/data/reviews_photos.csv'
DELIMITER ','
CSV HEADER;

COPY characteristics (id, product_id, name)
FROM '/Users/kevinkimchii/Documents/hackreactor/hrlax49/SDC/data/characteristics.csv'
DELIMITER ','
CSV HEADER;

COPY characteristic_reviews (id, characteristic_id, review_id, value)
FROM '/Users/kevinkimchii/Documents/hackreactor/hrlax49/SDC/data/characteristic_reviews.csv'
DELIMITER ','
CSV HEADER;

-- create indexes on tables
-- CREATE INDEX reviews_index ON reviews(product_id);
-- CREATE INDEX reviews_photos_index ON reviews_photos(review_id);
-- CREATE INDEX characteristics_index ON characteristics(product_id);
-- CREATE INDEX characteristic_reviews_index ON characteristic_reviews(characteristic_id);

-- resync primary keys
SELECT setval(pg_get_serial_sequence('reviews', 'id'), (SELECT MAX(id) FROM reviews)+1);
SELECT setval(pg_get_serial_sequence('reviews_photos', 'id'), (SELECT MAX(id) FROM reviews_photos)+1);
SELECT setval(pg_get_serial_sequence('characteristic_reviews', 'id'), (SELECT MAX(id) FROM characteristic_reviews)+1);